version: "3.9"

services:
  frontend:
    build:
      context: ./frontend

    ports:
      - "3000:3000"

  player-service:
    build:
      context: ./backend
      dockerfile: ./app/player-service/Dockerfile

    env_file:
      - ./backend/.env

    ports:
      - "8001:8000"

    depends_on:
      - db

  team-service:
    build:
      context: ./backend
      dockerfile: ./app/team-service/Dockerfile

    env_file:
      - ./backend/.env

    ports:
      - "8002:8000"

    depends_on:
      - db

  search-service:
    build:
      context: ./backend
      dockerfile: ./app/search-service/Dockerfile

    env_file:
      - ./backend/.env

    ports:
      - "8003:8000"

    depends_on:
      - db

  standings-service:
    build:
      context: ./backend
      dockerfile: ./app/standings-service/Dockerfile

    env_file:
      - ./backend/.env

    ports:
      - "8004:8000"

    depends_on:
      - db

  ai-query-service:
    build:
      context: ./backend
      dockerfile: ./app/ai-query-service/Dockerfile

    env_file:
      - ./backend/.env

    ports:
      - "8005:8000"

    depends_on:
      - db

  db:
    image: postgres:16

    restart: always

    env_file:
      - ./backend/.env

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
