version: "3.9"

services:
  frontend:
    build:
      context: ./frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - db

  db:
    image: postgres:16

    restart: always

    env_file:
      - ./backend/.env

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
