export const countryMap = {
  ALB: 'Albania 🇦🇱',
  ALG: 'Argelia 🇩🇿',
  ANG: 'Angola 🇦🇴',
  ARG: 'Argentina 🇦🇷',
  AUS: 'Australia 🇦🇺',
  AUT: 'Austria 🇦🇹',
  BAN: 'Bangladés 🇧🇩',
  BEL: 'Bélgica 🇧🇪',
  BFA: 'Burkina Faso 🇧🇫',
  BIH: 'Bosnia y Herzegovina 🇧🇦',
  BRA: 'Brasil 🇧🇷',
  BRB: 'Barbados 🇧🇧',
  BUL: 'Bulgaria 🇧🇬',
  CAN: 'Canadá 🇨🇦',
  CHI: 'Chile 🇨🇱',
  CIV: 'Costa de Marfil 🇨🇮',
  CMR: 'Camerún 🇨🇲',
  COD: 'República Democrática del Congo 🇨🇩',
  COL: 'Colombia 🇨🇴',
  CRC: 'Costa Rica 🇨🇷',
  CRO: 'Croacia 🇭🇷',
  CUW: 'Curazao 🇨🇼',
  CZE: 'República Checa 🇨🇿',
  DEN: 'Dinamarca 🇩🇰',
  DOM: 'República Dominicana 🇩🇴',
  ECU: 'Ecuador 🇪🇨',
  EGY: 'Egipto 🇪🇬',
  ENG: 'Inglaterra 🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  ESP: 'España 🇪🇸',
  FIN: 'Finlandia 🇫🇮',
  FRA: 'Francia 🇫🇷',
  GAB: 'Gabón 🇬🇦',
  GAM: 'Gambia 🇬🇲',
  GEO: 'Georgia 🇬🇪',
  GER: 'Alemania 🇩🇪',
  GHA: 'Ghana 🇬🇭',
  GNB: 'Guinea-Bissau 🇬🇼',
  GRE: 'Grecia 🇬🇷',
  GRN: 'Granada 🇬🇩',
  GUI: 'Guinea 🇬🇳',
  HAI: 'Haití 🇭🇹',
  HUN: 'Hungría 🇭🇺',
  IRL: 'Irlanda 🇮🇪',
  IRN: 'Irán 🇮🇷',
  IRQ: 'Irak 🇮🇶',
  ISL: 'Islandia 🇮🇸',
  ISR: 'Israel 🇮🇱',
  ITA: 'Italia 🇮🇹',
  JAM: 'Jamaica 🇯🇲',
  JPN: 'Japón 🇯🇵',
  KOR: 'Corea del Sur 🇰🇷',
  KVX: 'Kosovo 🇽🇰',
  LVA: 'Letonia 🇱🇻',
  MAR: 'Marruecos 🇲🇦',
  MEX: 'México 🇲🇽',
  MKD: 'Macedonia del Norte 🇲🇰',
  MLI: 'Mali 🇲🇱',
  MOZ: 'Mozambique 🇲🇿',
  MSR: 'Montserrat 🇲🇸',
  MTN: 'Mauritania 🇲🇷',
  NED: 'Países Bajos 🇳🇱',
  NGA: 'Nigeria 🇳🇬',
  NIR: 'Irlanda del Norte 🏴󠁧󠁢󠁮󠁧󠁿',
  NOR: 'Noruega 🇳🇴',
  NZL: 'Nueva Zelanda 🇳🇿',
  PAR: 'Paraguay 🇵🇾',
  PER: 'Perú 🇵🇪',
  POL: 'Polonia 🇵🇱',
  POR: 'Portugal 🇵🇹',
  ROU: 'Rumania 🇷🇴',
  RSA: 'Sudáfrica 🇿🇦',
  SCO: 'Escocia 🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  SEN: 'Senegal 🇸🇳',
  SKN: 'San Cristóbal y Nieves 🇰🇳',
  SRB: 'Serbia 🇷🇸',
  SUI: 'Suiza 🇨🇭',
  SUR: 'Surinam 🇸🇷',
  SVK: 'Eslovaquia 🇸🇰',
  SVN: 'Eslovenia 🇸🇮',
  SWE: 'Suecia 🇸🇪',
  TOG: 'Togo 🇹🇬',
  TUN: 'Túnez 🇹🇳',
  TUR: 'Turquía 🇹🇷',
  UKR: 'Ucrania 🇺🇦',
  URU: 'Uruguay 🇺🇾',
  USA: 'Estados Unidos 🇺🇸',
  UZB: 'Uzbekistán 🇺🇿',
  VEN: 'Venezuela 🇻🇪',
  WAL: 'Gales 🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  ZAM: 'Zambia 🇿🇲',
  ZIM: 'Zimbabue 🇿🇼',
};
